"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = """
$os\
[  ](bg:red)\
$username\
$directory\
[ ](fg:red)\
"""
right_format = """$git_branch $git_status $git_commit $all $cmd_duration"""


[username]
show_always = true
format = '[$user ](bg:red fg:white)'
disabled = false

[os]
style = "bg:red fg:white"
disabled = false

[os.symbols]
Arch = "  "
Artix = " "
CachyOS = " "
Linux = " "
Unknown = "  "

[directory]
format = "[$path](bg:red fg:white)"
truncation_length = 2
truncation_symbol = "…/"

[character]
format = "[$symbol](bg:red)"
success_symbol = "[](bold green)"
error_symbol = "[✗](bold red)"
disabled = true

[cmd_duration]
format = "[$duration]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = "  "
format = '[$symbol $branch (:$remote_branch)]($style)'

[git_status]
style = "bold blue"
format = "[$modified$deleted$untracked$ahead_behind]($style) "
modified = " "
deleted = " "
untracked = " "
ahead = " "
behind = " "
up_to_date = " "

[git_commit]
tag_symbol = '  '
format = '[$symbol($version)]($style)'

[c]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
format = '[$symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'
